INSERT IGNORE INTO movies
  (id, title, category, year, rating, duration, description, image)
VALUES
  (1, 'The Dark Knight', 'Action', 2008, 9.0, '152 min', 'Batman faces the chaos unleashed by the Joker in Gotham City.', 'the_dark_knight.webp'),
  (2, 'Inception', 'Sci-Fi', 2010, 8.8, '148 min', 'A thief is tasked with planting an idea inside someone''s mind.', 'inception.webp'),
  (3, 'The Shawshank Redemption', 'Drama', 1994, 9.3, '142 min', 'Two men bond in prison over years and find redemption.', 'shawshank_redemption.webp'),
  (4, 'Pulp Fiction', 'Crime', 1994, 8.9, '154 min', 'Lives of mobsters and others intertwine in violent tales.', 'pulp_fiction.webp'),
  (5, 'Forrest Gump', 'Drama', 1994, 8.8, '142 min', 'Life story of a man with a kind heart through history.', 'forrest_gump_fixed.webp'),
  (6, 'The Matrix', 'Sci-Fi', 1999, 8.7, '136 min', 'A hacker discovers the real world is a simulation.', 'matrix.webp'),
  (7, 'Interstellar', 'Sci-Fi', 2014, 8.6, '169 min', 'Explorers travel through a wormhole to save humanity.', 'interstellar.webp'),
  (8, 'Goodfellas', 'Crime', 1990, 8.7, '146 min', 'The story of Henry Hill and his life in the mob.', 'Goodfellas.webp'),
  (9, 'The Godfather', 'Crime', 1972, 9.2, '175 min', 'A mafia patriarch passes control of his empire to his son.', 'godfather.webp'),
  (10, 'Schindler''s List', 'Drama', 1993, 9.0, '195 min', 'Oskar Schindler saves Jewish workers during WWII.', 'schindlers_list.webp'),
  (11, 'Fight Club', 'Drama', 1999, 8.8, '139 min', 'An underground fight club forms with shocking results.', 'fight_club.webp'),
  (12, 'The Lord of the Rings', 'Fantasy', 2001, 8.8, '178 min', 'A Hobbit embarks on a journey to destroy the One Ring.', 'lordOfTheRings.webp'),
  (13, 'Star Wars: A New Hope', 'Sci-Fi', 1977, 8.6, '121 min', 'A young hero joins forces to save the galaxy.', 'star_wars.webp'),
  (14, 'The Silence of the Lambs', 'Thriller', 1991, 8.6, '118 min', 'An FBI cadet seeks help from a cannibal killer.', 'silenceLambs.webp'),
  (15, 'Saving Private Ryan', 'War', 1998, 8.6, '169 min', 'Soldiers go behind enemy lines to save a paratrooper.', 'savingPrivateRyan.webp'),
  (16, 'Gladiator', 'Action', 2000, 8.5, '155 min', 'A Roman general seeks vengeance against a corrupt emperor.', 'Gladiator.webp'),
  (17, 'Titanic', 'Romance', 1997, 7.9, '194 min', 'A young aristocrat falls in love on the ill-fated Titanic.', 'titanic.webp'),
  (18, 'Avatar', 'Sci-Fi', 2009, 7.8, '162 min', 'A Marine on Pandora struggles between orders and morality.', 'avatar.webp'),
  (19, 'The Departed', 'Crime', 2006, 8.5, '151 min', 'An undercover cop and a mole try to find each other.', 'departed.webp'),
  (20, 'Jurassic Park', 'Adventure', 1993, 8.2, '127 min', 'Paleontologists try to protect dinosaurs in a theme park.', 'jurassicPark.webp'),
  (21, 'The Avengers', 'Action', 2012, 8.0, '143 min', 'Earth''s mightiest heroes must stop Loki from destroying the world.', 'avengers.webp'),
  (22, 'Iron Man', 'Action', 2008, 7.9, '126 min', 'A billionaire builds an armored suit to fight evil.', 'iron_man.webp'),
  (23, 'Black Panther', 'Action', 2018, 7.3, '134 min', 'T''Challa returns home as king of Wakanda but faces a challenger.', 'black_panther.webp'),
  (24, 'Doctor Strange', 'Action', 2016, 7.5, '115 min', 'A surgeon becomes a Master of the Mystic Arts.', 'doctor_strange.webp'),
  (25, 'Guardians of the Galaxy', 'Action', 2014, 8.0, '121 min', 'A group of intergalactic criminals must save the universe.', 'guardians_of_the_galaxy.webp'),
  (26, 'Deadpool', 'Action', 2016, 8.0, '108 min', 'A mercenary with accelerated healing seeks revenge.', 'deadpool.webp'),
  (27, 'Wonder Woman', 'Action', 2017, 7.4, '141 min', 'An Amazonian princess becomes a hero in the world of men.', 'wonder_woman.webp'),
  (28, 'Aquaman', 'Action', 2018, 6.9, '143 min', 'Arthur Curry discovers he is heir to the underwater kingdom.', 'aquaman.webp'),
  (29, 'Thor: Ragnarok', 'Action', 2017, 7.9, '130 min', 'Thor must escape and save Asgard from Hela.', 'thor_ragnarok.webp'),
  (30, 'Spider-Man: Homecoming', 'Action', 2017, 7.4, '133 min', 'Peter Parker balances high school life with being Spider-Man.', 'spider_man.webp');
